Installation Instructions (pre-wiki)

.) install CentOS minimal

# curl https://raw.githubusercontent.com/QMailToaster/qmailtoaster-util/master/qt-bootstrap-1 >qt-bootstrap-1
# sh qt-bootstrap-1
(system will reboot)

# curl https://raw.githubusercontent.com/QMailToaster/qmailtoaster-util/master/qt-bootstrap-2 >qt-bootstrap-2
# sh qt-bootstrap-2

# qt-install
(script will complete the installation)
